### ISSUE TITLE
Add CSSJanus and explore a way to add a script to automatically generate rtl css

### ISSUE THREAD

**Issue by mooeypoo** [wikimedia/ToolforgeBundle#1]
CSS Janus is super useful and pretty mandatory if we want to support RTL; it exists as PHP and JS implementations.

The PHP one is here: https://github.com/cssjanus/php-cssjanus
The npm/JS one is here: https://github.com/cssjanus/cssjanus

We can try and see if we can have the php CSSJanus read the "regular" CSS files from the Symfony assets and then output a rtl script.

In npm-world, we do that with a grunt action to transform a file, but we can probably do that with the PHP  as well; it will definitely save us a whole lot of time and effort supporting RTL interfaces out of the box.

**Comment by samwilson** [comment]
This is being tracked here: https://phabricator.wikimedia.org/T208371
